version: '2'
services:
  app_ttce:
    build:
      context: ../
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www:z
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database_ttce"

  web_ttce:
    build:
      context: ../
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app_ttce
    ports:
      - 8088:80

  database_ttce:
    image: mysql:latest
    volumes:
      - dbdata_ttce:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata_ttce: